### ISSUE TITLE
Upgrade stripes to Jakarta EE 9+

### ISSUE THREAD

**Issue by TomOli** [StripesFramework/stripes#101]
Is posible to create new release of StripesFramework for compatibility with Jakarta EE 9.
rename packages javax -> jakarta
I have some project and I need to move from Tomcat 9.x -> Tomcat 10.x

**Comment by herrlado** [comment]
https://github.com/StripesFramework/stripes/pull/100

**Comment by rgrashel** [comment]
If you are on Stripes 1.6.0, you can build and try this branch that I just released:  https://github.com/StripesFramework/stripes/tree/1.6.0-Jakarta

I have not yet pushed this to the Maven repos.  But I know this works on both Tomcat 10.x as well as Payara 6.  All unit tests pass, all web tests pass.

**Comment by rgrashel** [comment]
Fixed in https://github.com/StripesFramework/stripes/pull/104.

Release: https://github.com/StripesFramework/stripes/releases/tag/1.6.0-Jakarta-beta
