### ISSUE TITLE
StripesRequestWrapper asumes that a request with json content-type should always have a body

### ISSUE THREAD

**Issue by juanpablo-santos** [StripesFramework/stripes#51]
From a restful point of view this is not always true, as there may be GET, DELETE, etc. requests that most of the time don't have a body. From a restless point of view, it could also happen. With stripes-1.7.0-beta1, in these situations, the following exception is raised on JsonContentTypeRequestWrapper line 49:

> com.fasterxml.jackson.databind.JsonMappingException: No content to map due to end-of-input
> at [Source: java.io.BufferedInputStream@5a9b6faf; line: 1, column: 1]

Specifically, the line
https://github.com/StripesFramework/stripes/blob/master/stripes/src/main/java/net/sourceforge/stripes/controller/StripesRequestWrapper.java#L125

is where it needs to also check that the request has a body to proceed with json body binding. PR with fix and test to reproduce the issue following in a minute.

**Comment by juanpablo-santos** [comment]
#52 merged 

thanks!

**Comment by vankeisb** [comment]
My pleasure !

**Comment by vankeisb** [comment]
Reopening : there's a problem with this commit :
9df1200bf04ee629eda5db0c8365afa63f2f6e6f

Webtests are failing starting from there. I only ran git bisect and found it. I'm pretty busy right now, @juanpablo-santos can you please have a look ? You can run the webtests easily on this version :

    git checkout master
    git checkout 9df1200bf04ee629eda5db0c8365afa63f2f6e6f
    mvn clean install -Pwebtests [-Dwebtests.browser=chrome -Dwebdriver.chrome.driver=/path/to/chromedriver]

**Comment by juanpablo-santos** [comment]
Hi @vankeisb,

think I found out what's happening. From [ServletRequest#getParameter](http://docs.oracle.com/javaee/6/api/javax/servlet/ServletRequest.html#getParameter%28java.lang.String%29)

> If the parameter data was sent in the request body, such as occurs with an HTTP POST request, then reading the body directly via getInputStream() or getReader() can interfere with the execution of this method.

To determine if the request has a body, StripesRequestWrapper peeks the request's reader, by reading the first byte and then peeking the reader. Turns out, it's enough to read that single byte to consume the entire reader, hence subsequent calls to `getParameterXXX` won't return anything.

So instead of peeking the request's reader, `StripesRequestWrapper` should do something like:

        boolean isPost = "POST".equalsIgnoreCase(request.getMethod());

        // Based on the content-type, decide if we need to create content-type
        // sensitive request wrappers for parameter handling
        if (contentType != null) {
            if (isPost && contentType.startsWith("multipart/form-data")) {
                constructMultipartWrapper(request);
            } else if (contentType.toLowerCase().contains("json")) {
                this.contentTypeRequestWrapper = new JsonContentTypeRequestWrapper();
                try {
                    this.contentTypeRequestWrapper.build(request);
                } catch( JsonMappingException jme ) {
                    log.debug( "json request without body / request body unmappable, proceed as usual" );
                    this.contentTypeRequestWrapper = null;
                } catch (IOException ioe) {
                    throw new StripesServletException("Could not construct JSON request wrapper.", ioe);
                }
            }
        }

Code above solves the issue, and webtests ran ok, I can reopen the branch and push the changes if you feel the code is ok.

However later on, if the request happens to have a json content-type, when building the `MergedParameterMap`, subsequent calls to `request.getParameterXXX` are made, so it may happen something similar to this issue. As I haven't had time to look into it, I'm guessing here..

regards,

**Comment by vankeisb** [comment]
Hi @juanpablo-santos,

Thanks for the analysis and pointers. I've had a look at the code and I confirm the bug.

I think Stripes should handle empty body and actual parsing errors differently. Empty body is ok, but malformed JSON should probably return a "400 : Bad Request". 

More generally, I don't understand the need for `JsonContentTypeRequestWrapper`. It seems that its role is to extract parameters from a request with JSON body. What's this used for ? If the body is a JSON payload, then why do we need to extract parameters from it ?

@rgrashel could you please explain the rationale behind this design ?

**Comment by vankeisb** [comment]
Ok I get it : it's used to bind the payload on the action bean by mapping JSON node paths to request params. Makes sense to have this done in the wrapper so that you don't need anything else to be changed. 

So I guess the only bug is the empty reader. 

Worse case : we need a dedicated `SafeReader` that attempts to read the first byte, and handles "empty" request reader.

**Comment by vankeisb** [comment]
I think I found a fix. 

`JsonContentTypeRequestWrapper` must be created only if `request.getContentLength() > 0`.

All tests are green, I'll commit that right away.

**Comment by rgrashel** [comment]
Thanks for this fix, Remi!

-- Rick
